### Schema
-- DROP DATABASE IF EXISTS coffee_db;
-- CREATE DATABASE coffee_db;
USE coffee_db;

CREATE TABLE Coffees (
id int NOT NULL AUTO_INCREMENT,
name varchar(225) NOT NULL,
drank BOOLEAN NOT NULL,
createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id)
);
